{{- define "examplelibrarychart.ui.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "examplelibrarychart.fullname" . }}
  labels:
    {{- include "examplelibrarychart.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.service).type | default "ClusterIP" }}
  ports:
    - port: {{ (.Values.service).port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "examplelibrarychart.selectorLabels" . | nindent 4 }}
{{- end -}}
